version: build.{build}

branches:
  only:
    - master

max_jobs: 1
skip_non_tags: true

image: Visual Studio 2019

install:
  - set QTDIR=C:\Qt\5.15\mingw81_64
  - set PATH=%QTDIR%\bin;C:\Qt\Tools\mingw810_64\bin;%PATH%

before_build:
  - gitversion /l console /output buildserver

build_script:
  - cmake -G "MinGW Makefiles" -B build -DCMAKE_PREFIX_PATH=%QTDIR%\lib\cmake
  - cd build/src
  - mingw32-make

after_build:
  - rm -r {antilogviewer_autogen,CMakeFiles,cmake_install.cmake,CMakeCache.txt,Makefile,qrc_resources.cpp,resources.qrc.depends} || true

artifacts:
  - path: build/src
    name: antilogviewer

deploy:
  description: 'Latest binaries'
  provider: GitHub
  auth_token:
    secure: BvYEGcp0DNNhWnLZB8+WKxtanQ0FEkzVyoyi6Vzv8EpOGpnXVbW7PwcytvsqgM1F
  force_update: true
  on:
    branch: master
    APPVEYOR_REPO_TAG: true