version: build.{build}

branches:
  only:
    - master

max_jobs: 1

image: Visual Studio 2017

install:
  - set QTDIR=C:\Qt\5.13\mingw73_64
  - set PATH=%QTDIR%\bin;C:\Qt\Tools\mingw730_64\bin;%PATH%

before_build:
  - gitversion /l console /output buildserver

build_script:
  - qmake antilogviewer.pro src
  - mingw32-make

after_build:
  - rm release/*.{o,h,cpp} || true
  - mkdir release\platforms
  - cp %QTDIR%\plugins\platforms\qwindows.dll release\platforms\
  - cp %QTDIR%\bin\{libgcc_s_seh-1.dll,libstdc++-6.dll,libwinpthread-1.dll,Qt5Core.dll,Qt5Gui.dll,Qt5Network.dll,Qt5Widgets.dll} release\

artifacts:
  - path: release
    name: antilogviewer
